Repository dooboolab/dooboo-ui, pull requests merged in 2019-11, with the labels that each got.

#28 Refactor [Button]
  package.json
  src/components/screen/ButtonSample.tsx
  src/components/screen/EditTextSample.tsx
  src/components/shared/Button/README.md
  src/components/shared/Button/index.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  storybook/stories/Button.stories.tsx
Labels: migration

#29 [Enhance] Add more props to EditText and update deprecated config
  .prettierrc.js
  package.json
  src/components/screen/EditTextSample.tsx
  src/components/shared/EditText/README.md
  src/components/shared/EditText/index.tsx
  src/components/shared/__tests__/EditText.test.tsx
  src/components/shared/__tests__/__snapshots__/EditText.test.tsx.snap
  storybook/stories/EditText.stories.tsx
  storybook/stories/index.js
Labels: enhancement

#30 [Release][Refactor] EditText
  package.json
  src/components/shared/EditText/index.tsx
  src/components/shared/__tests__/__snapshots__/EditText.test.tsx.snap
Labels: refactor, release

#31 Fix regression on [EditText] and release 0.3.4
  package.json
  src/components/shared/EditText/README.md
  src/components/shared/EditText/index.tsx
  src/components/shared/__tests__/__snapshots__/EditText.test.tsx.snap
Labels: bugfix, regression, release

#32 Componetize [SwitchToggle]
  .eslintignore
  .gitignore
  .npmignore
  README.md
  package.json
  src/components/shared/Accordion/CHANGELOG.md
  src/components/shared/Accordion/README.md
  src/components/shared/Accordion/package.json
  src/components/shared/Accordion/tsconfig.json
  src/components/shared/Accordion/yarn.lock
  src/components/shared/Button/CHANGELOG.md
  src/components/shared/Button/README.md
  src/components/shared/Button/package.json
  src/components/shared/Button/tsconfig.json
  src/components/shared/Button/yarn.lock
  src/components/shared/ButtonGroup/CHANGELOG.md
  src/components/shared/ButtonGroup/README.md
  src/components/shared/ButtonGroup/package.json
  src/components/shared/ButtonGroup/tsconfig.json
  src/components/shared/ButtonGroup/yarn.lock
  src/components/shared/CalendarCarousel/CHANGELOG.md
  src/components/shared/CalendarCarousel/package.json
  src/components/shared/CalendarCarousel/tsconfig.json
  src/components/shared/EditText/CHANGELOG.md
  src/components/shared/EditText/README.md
  src/components/shared/EditText/package.json
  src/components/shared/EditText/tsconfig.json
  src/components/shared/EditText/yarn.lock
  src/components/shared/GiftedChat/CHANGELOG.md
  src/components/shared/GiftedChat/README.md
  src/components/shared/GiftedChat/package.json
  src/components/shared/GiftedChat/tsconfig.json
  src/components/shared/GiftedChat/yarn.lock
  src/components/shared/LoadingIndicator/CHANGELOG.md
  src/components/shared/LoadingIndicator/README.md
  src/components/shared/LoadingIndicator/package.json
  src/components/shared/LoadingIndicator/tsconfig.json
  src/components/shared/LoadingIndicator/yarn.lock
  src/components/shared/SearchInput/CHANGELOG.md
  src/components/shared/SearchInput/README.md
  src/components/shared/SearchInput/index.tsx
  src/components/shared/SearchInput/package.json
  src/components/shared/SearchInput/tsconfig.json
  src/components/shared/SearchInput/yarn.lock
  src/components/shared/SwitchToggle/.npmignore
  src/components/shared/SwitchToggle/CHANGELOG.md
  src/components/shared/SwitchToggle/README.md
  src/components/shared/SwitchToggle/package.json
  src/components/shared/SwitchToggle/tsconfig.json
  src/components/shared/SwitchToggle/yarn.lock
  src/components/shared/__tests__/__snapshots__/SearchInput.test.tsx.snap
  tsconfigPackage.json
Labels: enhancement, feature

#33 [Release] sub packages release to 0.3.2
  CHANGELOGS.md
  package.json
  src/components/shared/Accordion/README.md
  src/components/shared/Accordion/package.json
  src/components/shared/Button/README.md
  src/components/shared/Button/package.json
  src/components/shared/ButtonGroup/README.md
  src/components/shared/ButtonGroup/package.json
  src/components/shared/CalendarCarousel/package.json
  src/components/shared/EditText/README.md
  src/components/shared/EditText/package.json
  src/components/shared/GiftedChat/README.md
  src/components/shared/GiftedChat/index.tsx
  src/components/shared/GiftedChat/package.json
  src/components/shared/LoadingIndicator/README.md
  src/components/shared/LoadingIndicator/package.json
  src/components/shared/SearchInput/README.md
  src/components/shared/SearchInput/index.tsx
  src/components/shared/SearchInput/package.json
  src/components/shared/SwitchToggle/README.md
  src/components/shared/SwitchToggle/index.tsx
  src/components/shared/SwitchToggle/package.json
  src/components/shared/__tests__/GiftedChat.test.tsx
  src/components/shared/__tests__/SearchInput.test.tsx
  src/components/shared/__tests__/SwitchToggle.test.tsx
Labels: documentation, enhancement

#34 [Release] Update sub packages version to 0.3.3
  src/components/shared/Accordion/README.md
  src/components/shared/Accordion/package.json
  src/components/shared/Button/README.md
  src/components/shared/Button/package.json
  src/components/shared/ButtonGroup/README.md
  src/components/shared/ButtonGroup/package.json
  src/components/shared/CalendarCarousel/package.json
  src/components/shared/EditText/README.md
  src/components/shared/EditText/package.json
  src/components/shared/GiftedChat/README.md
  src/components/shared/GiftedChat/package.json
  src/components/shared/LoadingIndicator/README.md
  src/components/shared/LoadingIndicator/package.json
  src/components/shared/SearchInput/README.md
  src/components/shared/SearchInput/package.json
  src/components/shared/SwitchToggle/README.md
  src/components/shared/SwitchToggle/package.json
Labels: release, typo

#36 [Accordion][Refactor] Release 4.0.0
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOGS.md
  package.json
  src/components/shared/Accordion/CHANGELOG.md
  src/components/shared/Accordion/README.md
  src/components/shared/Accordion/index.tsx
  src/components/shared/Accordion/package.json
  storybook/stories/Accordian.stories.tsx
Labels: refactor, release
