Repository dooboolab/dooboo-ui, pull requests merged in 2019-08, with the labels that each got.

#4 Add [LoadingIndicator]
  package.json
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/LoadingIndicatorSample.tsx
  src/components/shared/LoadingIndicator/index.d.ts
  src/components/shared/LoadingIndicator/index.js
  src/components/shared/__tests__/LoadingIndicator.test.tsx
  src/components/shared/__tests__/__snapshots__/LoadingIndicator.test.tsx.snap
  src/components/shared/index.js
  yarn.lock
Labels: feature

#5 Enhance [LoadingIndicator] docs
  README.md
  src/components/shared/DropdownItem/README.md
  src/components/shared/LoadingIndicator/README.md
  src/components/shared/LoadingIndicator/index.d.ts
  src/components/shared/LoadingIndicator/index.js
  src/components/shared/SwitchToggle/README.md
Labels: docs, enhancement

#6 Implement [Button] component
  .circleci/config.yml
  icons/facebook.png
  icons/facebook@2x.png
  icons/facebook@3x.png
  icons/google.png
  icons/google@2x.png
  icons/google@3x.png
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/ButtonSample.tsx
  src/components/screen/DropdownItemSample.tsx
  src/components/shared/Button/README.md
  src/components/shared/Button/index.d.ts
  src/components/shared/Button/index.js
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/utils/Icons.ts
Labels: feature

#7 Release 2.0.1
  CHANGELOGS.md
  README.md
  package.json
  src/components/shared/index.js
Labels: release

#8 Implement [EditText]
  .eslintrc.js
  README.md
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/EditTextSample.tsx
  src/components/shared/EditText/README.md
  src/components/shared/EditText/index.d.ts
  src/components/shared/EditText/index.js
  src/components/shared/__tests__/EditText.test.tsx
  src/components/shared/__tests__/__snapshots__/EditText.test.tsx.snap
  src/components/shared/index.d.ts
Labels: feature

#9 Feature/button group
  README.md
  index.js
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/ButtonGroupSample.tsx
  src/components/shared/Button/index.d.ts
  src/components/shared/ButtonGroup/README.md
  src/components/shared/ButtonGroup/index.d.ts
  src/components/shared/ButtonGroup/index.js
  src/components/shared/DropdownItem/index.d.ts
  src/components/shared/DropdownItem/index.js
  src/components/shared/EditText/README.md
  src/components/shared/LoadingIndicator/index.js
  src/components/shared/SwitchToggle/index.js
  src/components/shared/__tests__/ButtonGroup.test.tsx
  src/components/shared/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/shared/index.d.ts
  src/components/shared/index.js
Labels: feature

#10 enh/button
  package.json
  src/components/shared/Button/index.js
  src/components/shared/ButtonGroup/README.md
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
Labels: enhancement

#11 Migrate/tsc
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  .npmignore
  package.json
  src/App.tsx
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/ButtonGroupSample.tsx
  src/components/screen/ButtonSample.tsx
  src/components/screen/CalendarCarouselSample.tsx
  src/components/screen/DropdownItemSample.tsx
  src/components/screen/EditTextSample.tsx
  src/components/screen/LoadingIndicatorSample.tsx
  src/components/screen/SwitchToggleSample.tsx
  src/components/shared/Button/index.d.ts
  src/components/shared/Button/index.tsx
  src/components/shared/ButtonGroup/index.d.ts
  src/components/shared/ButtonGroup/index.tsx
  src/components/shared/CalendarCarousel/index.d.ts
  src/components/shared/CalendarCarousel/index.js
  src/components/shared/CalendarCarousel/index.tsx
  src/components/shared/DropdownItem/index.d.ts
  src/components/shared/DropdownItem/index.tsx
  src/components/shared/EditText/index.d.ts
  src/components/shared/EditText/index.js
  src/components/shared/EditText/index.tsx
  src/components/shared/LoadingIndicator/index.d.ts
  src/components/shared/LoadingIndicator/index.tsx
  src/components/shared/SwitchToggle/index.d.ts
  src/components/shared/SwitchToggle/index.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/ButtonGroup.test.tsx
  src/components/shared/__tests__/CalendarCarousel.test.tsx
  src/components/shared/__tests__/EditText.test.tsx
  src/components/shared/__tests__/LoadingIndicator.test.tsx
  src/components/shared/__tests__/SwitchToggle.test.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/components/shared/index.d.ts
  src/components/shared/index.ts
  tsconfig.json
  tsconfigBuild.json
  yarn.lock
Labels: migration

#12 Add error solution while starting project
  CONTRIBUTING.md
Labels: docs

#13 Feature/storybook integration
  .gitignore
  App.js
  ios/Podfile.lock
  ios/doobooWidgets/Info.plist
  package.json
  src/App.tsx
  src/components/navigation/SwitchNavigator.tsx
  storybook/addons.js
  storybook/index.js
  storybook/rn-addons.js
  storybook/stories/basicSample/Button/index.android.js
  storybook/stories/basicSample/Button/index.ios.js
  storybook/stories/basicSample/CenterView/index.js
  storybook/stories/basicSample/CenterView/style.js
  storybook/stories/basicSample/Welcome/index.js
  storybook/stories/basicSample/index.js
  storybook/stories/index.js
  storybook/stories/screen/ButtonGroupSample.stories.tsx
  storybook/stories/screen/ButtonSample.stories.tsx
  yarn.lock
Labels: feature

#14 change all style prop to receive flattened styles
  src/components/shared/Button/index.tsx
  src/components/shared/ButtonGroup/index.tsx
  src/components/shared/DropdownItem/index.tsx
  src/components/shared/EditText/index.tsx
  src/components/shared/LoadingIndicator/index.tsx
  src/components/shared/SwitchToggle/index.tsx
  src/components/shared/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
Labels: enhancement

#15 Upgrade packages
  package.json
  yarn.lock
Labels: upgrade packages

#16 Add SwitchToggle and remove screen
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/SwitchToggleSample.tsx
  storybook/decorators.tsx
  storybook/stories/SwitchToggle.stories.tsx
  storybook/stories/basicSample/Button/index.android.js
  storybook/stories/basicSample/Button/index.ios.js
  storybook/stories/basicSample/CenterView/index.js
  storybook/stories/basicSample/CenterView/style.js
  storybook/stories/basicSample/Welcome/index.js
  storybook/stories/basicSample/index.js
  storybook/stories/index.js
  storybook/stories/screen/ButtonGroupSample.stories.tsx
  storybook/stories/screen/ButtonSample.stories.tsx
Labels: enhancement, feature
