Repository dooboolab/dooboo-ui, pull requests merged in 2019-12, with the labels that each got.

#52 [Feat/RadioButton] Init shared/RadioButton component
  src/components/shared/RadioButton/CHANGELOG.md
  src/components/shared/RadioButton/README.md
  src/components/shared/RadioButton/index.tsx
  src/components/shared/RadioButton/tsconfig.json
Labels: branch

#54 [Feature] Add [ThemeProvider]
  src/providers/Theme/CHANGELOG.md
  src/providers/Theme/README.md
  src/providers/Theme/createCtx.ts
  src/providers/Theme/index.tsx
  src/providers/Theme/theme.ts
  src/providers/Theme/tsconfig.json
  src/providers/Theme/yarn.lock
Labels: feature

#56 [Feature][Branch][Init] AutoComplete
  android/.project
  android/app/.project
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/AutoCompleteSample.tsx
  src/components/shared/AutoComplete/CHANGELOG.md
  src/components/shared/AutoComplete/README.md
  src/components/shared/AutoComplete/RenderInput.tsx
  src/components/shared/AutoComplete/dummyData.ts
  src/components/shared/AutoComplete/index.tsx
  src/components/shared/AutoComplete/renderOptions.tsx
  src/components/shared/AutoComplete/styles.ts
  src/components/shared/AutoComplete/tsconfig.json
  src/components/shared/AutoComplete/types.ts
  src/components/shared/index.ts
  src/providers/Theme/CHANGELOG.md
  src/providers/Theme/README.md
  src/providers/Theme/createCtx.ts
  src/providers/Theme/index.tsx
  src/providers/Theme/theme.ts
  src/providers/Theme/tsconfig.json
  src/providers/Theme/yarn.lock
Labels: feature

#57 [Feature][Branch][Init]
  App.js
  babel.config.js
  ios/Podfile.lock
  ios/doobooWidgets.xcodeproj/project.pbxproj
  package.json
  src/components/shared/AutoComplete/README.md
  src/components/shared/AutoComplete/index.tsx
  src/components/shared/AutoComplete/styles.ts
  yarn.lock
Labels: branch, feature

#58 [Feature][Branch][bugfix] AutoComplete bugfix
  src/components/shared/AutoComplete/renderInput.tsx
Labels: branch, bugfix, feature

#49 [Feature][Branch] Add slider storybook file, Implement basic Rail, PanResponder
  ios/Podfile.lock
  package.json
  src/components/shared/Slider/Rail.tsx
  src/components/shared/Slider/index.tsx
  src/components/shared/__tests__/__snapshots__/Slider.test.tsx.snap
  storybook/stories/Slider.stories.tsx
  storybook/stories/index.js
  yarn.lock
Labels: feature

#48 [Enhance] SearchInput
  .gitignore
  .vscode/settings.json
  src/components/shared/SearchInput/index.tsx
  storybook/stories/SearchInput.stories.tsx
Labels: enhancement

#62 [Feature][Branch][Init] Select
  src/components/shared/Select/CHANGELOG.md
  src/components/shared/Select/README.md
  src/components/shared/Select/index.tsx
  src/components/shared/Select/tsconfig.json
  src/components/shared/Select/yarn.lock
  storybook/stories/Select.stories.tsx
  storybook/stories/index.js
Labels: feature

#61 [Feature][Branch] create snackbar component
  .vscode/settings.json
  src/components/shared/Snackbar/CHANGELOG.md
  src/components/shared/Snackbar/README.md
  src/components/shared/Snackbar/index.tsx
  src/components/shared/Snackbar/tsconfig.json
  src/components/shared/__tests__/Snackbar.test.tsx
  src/components/shared/__tests__/__snapshots__/Snackbar.test.tsx.snap
  storybook/stories/Snackbar.stories.tsx
  storybook/stories/index.js
Labels: branch, feature

#71 [Feature][Branch][init][storybook] add a minor design change
  App.js
  storybook/stories/AutoComplete.stories.tsx
Labels: branch, feature, stories

#69 Bump typescript minor version to 3.7
  package.json
  yarn.lock
Labels: update packages

#64 [Feature][Branch][Rating] Initial implement for rating component
  src/components/shared/Rating/CHANGELOG.md
  src/components/shared/Rating/README.md
  src/components/shared/Rating/images/Star.png
  src/components/shared/Rating/images/UnStar.png
  src/components/shared/Rating/index.tsx
  src/components/shared/Rating/tsconfig.json
  src/components/shared/__tests__/Rating.test.tsx
  src/components/shared/__tests__/__snapshots__/Rating.test.tsx.snap
  storybook/stories/Rating.stories.tsx
  storybook/stories/index.js
Labels: branch, feature, rating

#77 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#81 [Feature][Branch][Rating] Refactoring and add README file
  src/components/shared/Rating/README.md
  src/components/shared/Rating/index.tsx
  src/components/shared/__tests__/__snapshots__/Rating.test.tsx.snap
  storybook/stories/Rating.stories.tsx
Labels: branch, rating, refactor

#75 [Feature][Branch] Select -> "Root" section
  src/components/shared/Select/README.md
  src/components/shared/Select/index.tsx
  src/components/shared/__tests__/Select.test.tsx
  src/components/shared/__tests__/__snapshots__/Select.test.tsx.snap
  storybook/stories/Select.stories.tsx
Labels: branch, feature, select

#63 [Feature][Branch][Snackbar] Add timer feature on Snackbar
  src/components/shared/Snackbar/README.md
  src/components/shared/Snackbar/index.tsx
  src/components/shared/__tests__/Snackbar.test.tsx
  src/components/shared/__tests__/__snapshots__/Snackbar.test.tsx.snap
  storybook/stories/Snackbar.stories.tsx
Labels: branch, feature, snackbar

#89 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#90 Integrate lerna to manage mono repo efficiently
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  lerna.json
  package.json
  src/components/shared/Accordion/package.json
  src/components/shared/Accordion/tsconfig.json
  src/components/shared/Button/package.json
  src/components/shared/Button/tsconfig.json
  src/components/shared/ButtonGroup/package.json
  src/components/shared/ButtonGroup/tsconfig.json
  src/components/shared/CalendarCarousel/package.json
  src/components/shared/CalendarCarousel/tsconfig.json
  src/components/shared/EditText/index.tsx
  src/components/shared/EditText/package.json
  src/components/shared/EditText/tsconfig.json
  src/components/shared/GiftedChat/package.json
  src/components/shared/GiftedChat/tsconfig.json
  src/components/shared/LoadingIndicator/package.json
  src/components/shared/LoadingIndicator/tsconfig.json
  src/components/shared/SearchInput/package.json
  src/components/shared/SearchInput/tsconfig.json
  src/components/shared/SwitchToggle/package.json
  src/components/shared/SwitchToggle/tsconfig.json
  src/providers/Theme/.npmignore
  src/providers/Theme/package.json
  tsconfigBuild.json
  tsconfigPackage.json
  yarn.lock
Labels: integration, update packages

#91 Upgrade react-native to 0.61.5
  .flowconfig
  .gitignore
  .prettierrc.js
  android/app/build.gradle
  android/app/src/main/java/com/dooboowidgets/MainActivity.java
  android/app/src/main/java/com/dooboowidgets/MainApplication.java
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  ios/Podfile
  ios/Podfile.lock
  ios/doobooWidgets.xcodeproj/project.pbxproj
  ios/doobooWidgets.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/doobooWidgets.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  ios/doobooWidgets/Info.plist
  ios/doobooWidgetsTests/doobooWidgetsTests.m
  package.json
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/GiftedChat.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/SwitchToggle.test.tsx.snap
  yarn.lock
Labels: upgrade

#95 [Release] Add ability to render [EditText] into row
  .prettierrc.js
  .vscode/settings.json
  package.json
  src/components/shared/Button/index.tsx
  src/components/shared/EditText/CHANGELOG.md
  src/components/shared/EditText/README.md
  src/components/shared/EditText/index.tsx
  src/components/shared/EditText/package.json
  src/components/shared/GiftedChat/index.tsx
  src/components/shared/GiftedChat/package.json
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/ButtonGroup.test.tsx
  src/components/shared/__tests__/CalendarCarousel.test.tsx
  src/components/shared/__tests__/EditText.test.tsx
  src/components/shared/__tests__/GiftedChat.test.tsx
  src/components/shared/__tests__/LoadingIndicator.test.tsx
  src/components/shared/__tests__/SearchInput.test.tsx
  src/components/shared/__tests__/__snapshots__/EditText.test.tsx.snap
  storybook/stories/EditText.stories.tsx
  storybook/stories/SearchInput.stories.tsx
  yarn.lock
Labels: enhancement, feature, release

#93 [Feature][Branch][Select] quick fix of "Root" section
  src/components/shared/Select/index.tsx
  src/components/shared/__tests__/Select.test.tsx
Labels: select

#102 Update circleci
  .circleci/config.yml
  package.json
  src/components/shared/Accordion/package.json
  src/components/shared/Button/package.json
  src/components/shared/ButtonGroup/package.json
  src/components/shared/CalendarCarousel/package.json
  src/components/shared/EditText/package.json
  src/components/shared/GiftedChat/package.json
  src/components/shared/LoadingIndicator/package.json
  src/components/shared/SearchInput/package.json
  src/components/shared/SwitchToggle/package.json
  src/providers/Theme/package.json
Labels: ci

#103 [Feature] Add feature LoadingIndicator and Update README.md
  ios/Podfile.lock
  src/components/shared/EditText/README.md
  src/components/shared/LoadingIndicator/README.md
  src/components/shared/LoadingIndicator/index.tsx
  src/components/shared/__tests__/LoadingIndicator.test.tsx
  src/components/shared/__tests__/__snapshots__/LoadingIndicator.test.tsx.snap
  storybook/stories/LoadingIndicator.stories.tsx
  storybook/stories/index.js
Labels: feature

#105 [Enhancement] Upgrade circleci config
  .circleci/config.yml
Labels: ci, enhancement

#79 [Feature][Branch] enable custom styling for Snackbar component
  src/components/shared/Snackbar/index.tsx
  src/components/shared/__tests__/__snapshots__/Snackbar.test.tsx.snap
  storybook/stories/Snackbar.stories.tsx
Labels: branch, feature, snackbar

#92 [Feature][WIP] Auto complete
  src/components/shared/AutoComplete/README.md
  src/components/shared/AutoComplete/index.tsx
  src/components/shared/AutoComplete/renderOptions.tsx
  src/components/shared/AutoComplete/types.ts
  storybook/stories/AutoComplete.stories.tsx
Labels: autocomplete, branch, feature

#98 [Feature][Branch][Rating] Update test code
  src/components/shared/__tests__/Rating.test.tsx
  src/components/shared/__tests__/__snapshots__/Rating.test.tsx.snap
Labels: feature, rating

#72 [Feature][Branch] Add AutoComplete Render Options
  src/components/shared/AutoComplete/index.tsx
  src/components/shared/AutoComplete/renderOptions.tsx
  src/components/shared/AutoComplete/styles.ts
  src/components/shared/AutoComplete/types.ts
Labels: autocomplete, branch, feature, wip
