Repository dooboolab/dooboo-ui, pull requests merged in 2019-09, with the labels that each got.

#20 Storybook/navigation sync and plugins
  package.json
  storybook/addons.js
  storybook/index.js
  storybook/stories/Accordian.stories.tsx
  storybook/stories/Button.stories.tsx
  yarn.lock
Labels: enhancement

#21 Updates doc for starting with storybook
  CONTRIBUTING.md
Labels: docs

#22 Add SearchInput
  icons/magnifier.png
  package.json
  src/components/shared/SearchInput/README.md
  src/components/shared/SearchInput/index.tsx
  src/components/shared/__tests__/SearchInput.test.tsx
  src/components/shared/__tests__/__snapshots__/SearchInput.test.tsx.snap
  src/utils/Icons.ts
  storybook/addons.js
  storybook/index.js
  storybook/stories/Button.stories.tsx
  storybook/stories/ButtonGroup.stories.tsx
  storybook/stories/SearchInput.stories.tsx
  storybook/stories/index.js
  yarn.lock
Labels: feature

#23 Enh/ts
  environment.d.ts
  package.json
  src/components/screen/ButtonSample.tsx
  src/components/screen/CalendarCarouselSample.tsx
  src/components/screen/EditTextSample.tsx
  src/components/screen/LoadingIndicatorSample.tsx
  src/components/shared/Button/index.tsx
  src/components/shared/CalendarCarousel/index.tsx
  src/components/shared/SearchInput/index.tsx
  src/components/shared/SwitchToggle/index.tsx
  src/components/shared/__tests__/Button.test.tsx
  src/components/shared/__tests__/ButtonGroup.test.tsx
  src/components/shared/__tests__/CalendarCarousel.test.tsx
  src/components/shared/__tests__/EditText.test.tsx
  src/components/shared/__tests__/LoadingIndicator.test.tsx
  src/components/shared/__tests__/SearchInput.test.tsx
  src/contexts/index.ts
  src/utils/Icons.ts
  storybook/decorators.tsx
  storybook/stories/Accordian.stories.tsx
  storybook/stories/Button.stories.tsx
  storybook/stories/ButtonGroup.stories.tsx
  storybook/stories/SearchInput.stories.tsx
  storybook/stories/SwitchToggle.stories.tsx
  tsconfig.json
  tsconfigBuild.json
  yarn.lock
Labels: types
