Repository dooboolab/dooboo-ui, pull requests merged in 2020-10, with the labels that each got.

#356 Release 0.0.22
  lib/package.json
  main/Checkbox/Checkbox.tsx
  main/Checkbox/CheckboxGroup.tsx
  main/Checkbox/index.tsx
  main/__assets__/mark.png
  main/index.ts
  package.json
  packages/DatePicker/Calendar/Calendar.tsx
  packages/DatePicker/Calendar/CalendarDate.tsx
  packages/DatePicker/Calendar/CalendarMonth.tsx
  packages/DatePicker/Calendar/CalendarWeekDays.tsx
  packages/DatePicker/DateInput.tsx
  packages/DatePicker/PickerCalendar.tsx
  packages/DatePicker/README.md
  packages/DatePicker/assets/calendar.png
  packages/DatePicker/index.tsx
  packages/PinchZoom/PinchZoom.example.tsx
  packages/PinchZoom/README.md
  packages/PinchZoom/index.tsx
  packages/PinchZoom/utils.ts
  packages/Tables/CheckBox.tsx
  packages/Tables/assets/mark.png
  packages/__tests__/DatePicker.test.tsx
  packages/__tests__/PinchZoom.test.tsx
  packages/__tests__/__snapshots__/DatePicker.test.tsx.snap
  packages/__tests__/__snapshots__/PinchZoom.test.tsx.snap
  packages/__tests__/__snapshots__/Tables.test.tsx.snap
  packages/__tests__/data/capturedGesture.ts
  stories/dooboo-ui/DatePicker.stories.tsx
  stories/dooboo-ui/PinchZoom.stories.tsx
  yarn.lock
Labels: release

#358 Fix/pinch zoom
  packages/PinchZoom/index.tsx
  packages/__tests__/__snapshots__/PinchZoom.test.tsx.snap
Labels: bugfix

#359 refactor: improve `variant` of interface [Badge]
  main/Badge/index.tsx
Labels: types
