Repository dooboolab/dooboo-ui, pull requests merged in 2020-09, with the labels that each got.

#321 Major refactoring [Accordion]
  CHANGELOGS.md
  main/Accordion/AccordionItem.tsx
  main/Accordion/README.md
  main/Accordion/index.tsx
  main/__tests__/Accordion.test.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
  stories/dooboo-ui/Accordion.stories.tsx
Labels: refactor

#299 docs : Update Slider component README.md
  main/Slider/README.md
Labels: documentation

#329 docs: replace pixelly images in README [Slider]
  main/Slider/README.md
Labels: documentation

#323 [Feature] Implement Card
  main/Card/README.md
  main/Card/index.tsx
  main/Card/styles.tsx
  main/__tests__/Card.test.tsx
  main/__tests__/__snapshots__/Card.test.tsx.snap
  main/index.ts
  stories/dooboo-ui/Card.stories.tsx
  stories/index.ts
Labels: feature

#325 [Feature] Checkbox component
  main/CheckBox/index.tsx
  main/Checkbox/Checkbox.tsx
  main/Checkbox/CheckboxGroup.tsx
  main/Checkbox/README.md
  main/Checkbox/index.tsx
  main/__assets__/check_tick.png
  main/__tests__/Checkbox.test.tsx
  main/__tests__/__snapshots__/Card.test.tsx.snap
  main/__tests__/__snapshots__/Checkbox.test.tsx.snap
  main/index.ts
  stories/dooboo-ui/Checkbox.stories.tsx
  stories/index.ts
Labels: feature

#332 [Feature][Datepicker] Component
  .vscode/settings.json
  main/DatePicker/Calendar/Calendar.tsx
  main/DatePicker/Calendar/CalendarDate.tsx
  main/DatePicker/Calendar/CalendarMonth.tsx
  main/DatePicker/Calendar/CalendarWeekDays.tsx
  main/DatePicker/DateInput.tsx
  main/DatePicker/PickerCalendar.tsx
  main/DatePicker/README.md
  main/DatePicker/index.tsx
  main/__assets__/calendar.png
  main/__tests__/DatePicker.test.tsx
  main/__tests__/__snapshots__/DatePicker.test.tsx.snap
  main/index.ts
  package-lock.json
  stories/dooboo-ui/DatePicker.stories.tsx
  stories/index.ts
Labels: feature

#328 Upgrade storybook packages; Add a AsyncStorage package
  App.tsx
  package.json
  yarn.lock
Labels: environment

#327 [Rating] Correct style px units; Update test code
  main/Rating/index.tsx
  main/__tests__/Rating.test.tsx
  main/__tests__/__snapshots__/Rating.test.tsx.snap
Labels: refactor, testing

#336 Add ESlint padding line rules; Update VSCode lint settings
  .eslintrc.js
  .vscode/settings.json
Labels: environment

#349 test: remove snapshots from the test [DatePicker]
  main/__tests__/DatePicker.test.tsx
  main/__tests__/__snapshots__/DatePicker.test.tsx.snap
Labels: testing

#348 Refactor Button Styles
  main/Button/README.md
  main/Button/index.tsx
  main/__tests__/__snapshots__/Button.test.tsx.snap
  stories/dooboo-ui/Button.stories.tsx
  stories/dooboo-ui/EditText.stories.tsx
Labels: enhancement

#352 build: update eslintrc.js
  .eslintrc.js
Labels: environment

#354 Update README.md
  README.md
Labels: documentation
