Repository dooboolab/dooboo-ui, pull requests merged in 2020-06, with the labels that each got.

#201 Accordion enhancement
  main/Accordion/index.tsx
  stories/dooboo-ui/Accordion.stories.tsx
Labels: enhancement

#205 Add tests to [Accordion]
  .circleci/config.yml
  .gitignore
  codecov.yml
  main/Accordion/index.tsx
  main/__tests__/Accordion.test.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
Labels: core, testing

#208 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#203 Button enhancement
  main/Button/index.tsx
  main/__tests__/__snapshots__/Button.test.tsx.snap
  stories/dooboo-ui/Button.stories.tsx
Labels: enhancement

#204 Radio button error fix
  main/EditText/index.tsx
  main/RadioButton/index.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  main/__tests__/__snapshots__/RadioButton.test.tsx.snap
  stories/dooboo-ui/EditText.stories.tsx
  stories/dooboo-ui/RadioButton.stories.tsx
Labels: enhancement

#206 EditText Minor update
  main/EditText/index.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  stories/dooboo-ui/EditText.stories.tsx
Labels: enhancement

#214 Fix `Style property 'xxx' is not supported by native animated module` iOS runtime error
  main/Accordion/index.tsx
  main/RadioButton/index.tsx
  main/Slider/index.tsx
Labels: bugfix

#213 Fix wrong storybook path in postinstall
  package.json
Labels: enhancement

#215 Refactor [Accordion]
  .gitignore
  .ncurc.json
  main/Accordion/AccordionItem.tsx
  main/Accordion/Arrow.tsx
  main/Accordion/README.md
  main/Accordion/index.tsx
  main/__tests__/Accordion.test.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
  package.json
  packages/CalendarCarousel/package.json
  packages/CalendarCarousel/yarn.lock
  packages/GiftedChat/package.json
  packages/GiftedChat/yarn.lock
  packages/PinchZoomSliderModal/package.json
  packages/PinchZoomSliderModal/yarn.lock
  packages/Snackbar/package.json
  packages/Snackbar/yarn.lock
  packages/TinderCard/package.json
  packages/TinderCard/yarn.lock
  packages/theme/package.json
  packages/theme/yarn.lock
  stories/dooboo-ui/Accordion.stories.tsx
  stories/packages/Snackbar.stories.tsx
  yarn.lock
Labels: refactor

#216 [Enhance][Refactor] Accordion
  main/Accordion/AccordionItem.tsx
  main/Accordion/README.md
  main/Accordion/index.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
  stories/dooboo-ui/Accordion.stories.tsx
Labels: enhancement, refactor

#218 [Bugfix]Fix that Tindercard can't import appropriate modules because of wrong path
  stories/packages/TinderCard.stories.tsx
Labels: bugfix, typo
