Repository dooboolab/dooboo-ui, pull requests merged in 2020-08, with the labels that each got.

#275 test: update the test snapshot [CalendarCarousel]
  packages/__tests__/__snapshots__/CalendarCarousel.test.tsx.snap
Labels: testing

#276 Change Usage in ButtonGruop/README.md
  main/ButtonGroup/README.md
Labels: documentation

#278 test: update snapshot [CalendarCarousel]
  packages/__tests__/__snapshots__/CalendarCarousel.test.tsx.snap
Labels: testing

#279 docs(CONTRIBUTING.md): change command for run storybook web server
  CONTRIBUTING.md
Labels: documentation

#280 Fix: checkBox and Snackbar.test file value defined but is used
  packages/Tables/CheckBox.tsx
  packages/__tests__/Snackbar.test.tsx
Labels: refactor

#277 docs: added image preview in Rating/README.md
  main/Rating/README.md
Labels: documentation

#283 [Slider]Refactor: add type to getPercentByValue
  main/Slider/utils.ts
Labels: types

#291 Change the CONTRIBUTING.md url
  README.md
Labels: documentation

#290 Fixed to storybook link is broken for building storybook
  doc/.storybook/webpack.config.js
  doc/package.json
  doc/postbuild.sh
Labels: bugfix

#300 Enhance storybook docs
  doc/.storybook/config.js
  doc/.storybook/webpack.config.js
  doc/package.json
  doc/src/Components/Accordion/Accordion.stories.mdx
  doc/src/Components/Accordion/examples/index.tsx
  doc/src/Components/Button/Button.stories.mdx
  doc/src/Components/ButtonGroup/ButtonGroup.stories.mdx
  doc/src/Components/EditText/EditText.stories.mdx
  doc/src/Components/LoadingIndicator/LoadingInicator.stories.mdx
  doc/src/Components/RadioButton/RadioButton.stories.mdx
  doc/src/Components/SearchInput/SearchInput.stories.mdx
  doc/src/Components/Select/Select.stories.mdx
  doc/src/Components/Slider/Slider.stories.mdx
  doc/src/Components/SwitchToggle/SwitchToggle.stories.mdx
  doc/src/Packages/PinchZoomSliderModal/PinchZoomSliderModal.stories.mdx
  doc/src/Packages/Snackbar/Snackbar.stories.mdx
  doc/src/Packages/Snackbar/examples.tsx
  doc/src/Packages/Tables/Tables.stories.mdx
  doc/src/introduce.stories.mdx
  doc/yarn.lock
  package.json
  packages/Snackbar/Snackbar.tsx
Labels: enhancement

#301 Change Container Style in stories/Button
  stories/dooboo-ui/Button.stories.tsx
Labels: enhancement, ui

#297 fix: correct text input password ellipsis issue
  main/EditText/index.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  stories/dooboo-ui/EditText.stories.tsx
Labels: bugfix

#308 Updated Readme.md of Calendar Carousel
  package.json
  packages/CalendarCarousel/README.md
  packages/CalendarCarousel/index.tsx
  packages/CalendarCarousel/package-lock.json
  packages/CalendarCarousel/package.json
  stories/packages/CalendarCarousel.stories.tsx
  yarn.lock
Labels: documentation, enhancement

#320 Major refactoring done in [EditText]
  doc/src/Components/Accordion/Accordion.stories.mdx
  doc/src/Components/Accordion/examples/index.tsx
  doc/src/Components/Button/Button.stories.mdx
  doc/src/Components/EditText/EditText.stories.mdx
  main/Accordion/README.md
  main/Button/README.md
  main/Button/hooks/customHooks.ts
  main/Button/hooks/index.ts
  main/Button/hooks/utils/getNode.native.ts
  main/Button/hooks/utils/getNode.ts
  main/Button/index.tsx
  main/CheckBox/index.tsx
  main/EditText/README.md
  main/EditText/index.tsx
  main/SearchInput/index.tsx
  main/Select/Arrow.tsx
  main/Select/Item.tsx
  main/Select/Select.tsx
  main/Select/SelectItem.tsx
  main/Select/index.tsx
  main/SwitchToggle/index.tsx
  main/Tooltip/index.tsx
  main/__assets__/checkbox-mark.png
  main/__tests__/Accordion.test.tsx
  main/__tests__/Button.test.tsx
  main/__tests__/SearchInput.test.tsx
  main/__tests__/Select.test.tsx
  main/__tests__/SwitchToggle.test.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
  main/__tests__/__snapshots__/Button.test.tsx.snap
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  main/__tests__/__snapshots__/SearchInput.test.tsx.snap
  main/__tests__/__snapshots__/Select.test.tsx.snap
  main/__tests__/__snapshots__/SwitchToggle.test.tsx.snap
  package.json
  packages/GiftedChat/README.md
  stories/dooboo-ui/Accordion.stories.tsx
  stories/dooboo-ui/Button.stories.tsx
  stories/dooboo-ui/EditText.stories.tsx
  stories/dooboo-ui/LoadingIndicator.stories.tsx
  stories/dooboo-ui/SearchInput.stories.tsx
  stories/dooboo-ui/Select.stories.tsx
  yarn.lock
Labels: refactor
