Repository dooboolab/dooboo-ui, pull requests merged in 2020-02, with the labels that each got.

#170 [Feature][Branch][AutoComplete] fix sizes on horizontal orientation
  package.json
  src/components/screen/AutoCompleteSample.tsx
  src/components/shared/AutoComplete/index.tsx
  src/components/shared/AutoComplete/styles.ts
  src/components/shared/AutoComplete/types.ts
  storybook/stories/AutoComplete.stories.tsx
  yarn.lock
Labels: branch, feature, lib/autocomplete

#172 Implement PinchZoomSliderModal
  .circleci/config.yml
  README.md
  src/components/shared/PinchZoomSliderModal/CHANGELOG.md
  src/components/shared/PinchZoomSliderModal/README.md
  src/components/shared/PinchZoomSliderModal/index.tsx
  src/components/shared/PinchZoomSliderModal/package.json
  src/components/shared/PinchZoomSliderModal/tsconfig.json
  src/components/shared/PinchZoomSliderModal/yarn.lock
  src/components/shared/index.ts
  storybook/stories/PinchZoomSliderModal.stories.tsx
  storybook/stories/index.js
Labels: feature, good first element

#174 [Bugfix][Slider] Fix layout on orientation change
  src/components/shared/Slider/index.tsx
  storybook/stories/Slider.stories.tsx
Labels: bugfix, lib/slider

#175 [Enhance][Slider] Set lerna package for Slider
  README.md
  src/components/shared/Slider/CHANGELOG.md
  src/components/shared/Slider/package.json
  src/components/shared/Slider/tsconfig.json
  src/components/shared/Slider/yarn.lock
Labels: enhancement, lib/slider

#171 [Feature][TinderCard] Update tinder card
  src/components/shared/TinderCard/README.md
  src/components/shared/TinderCard/index.tsx
  src/components/shared/__tests__/__snapshots__/TinderCard.test.tsx.snap
  storybook/stories/TinderCard.stories.tsx
  storybook/stories/asset/dummyData/data.js
Labels: enhancement

#128 Update README.md
  src/components/shared/Rating/README.md
Labels: documentation

#176 Enhance [PinchZoomSliderModal] with ViewPager
  ios/Podfile.lock
  package.json
  src/components/shared/PinchZoomSliderModal/CHANGELOG.md
  src/components/shared/PinchZoomSliderModal/index.tsx
  src/components/shared/PinchZoomSliderModal/package.json
  src/components/shared/PinchZoomSliderModal/yarn.lock
  src/components/shared/Slider/yarn.lock
  yarn.lock
Labels: enhancement

#173 [Feature][Snackbar] Provide Snackbar provider
  README.md
  jest.config.js
  src/components/navigation/SwitchNavigator.tsx
  src/components/screen/SnackbarSample.tsx
  src/components/shared/Snackbar/README.md
  src/components/shared/Snackbar/Snackbar.tsx
  src/components/shared/Snackbar/index.tsx
  src/components/shared/__tests__/Snackbar.test.tsx
  src/components/shared/__tests__/__snapshots__/Button.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/GiftedChat.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/Slider.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/Snackbar.test.tsx.snap
  src/components/shared/__tests__/__snapshots__/SwitchToggle.test.tsx.snap
  storybook/stories/Snackbar.stories.tsx
Labels: feature
