Repository dooboolab/dooboo-ui, pull requests merged in 2020-07, with the labels that each got.

#219 [RadioButton] Add the story to storybook web; Refactor the story
  stories/dooboo-ui/RadioButton.stories.tsx
Labels: refactor

#226 [Accordion]Refactoring for V2
  main/Accordion/AccordionItem.tsx
  main/Accordion/README.md
  main/Accordion/index.tsx
  main/__tests__/Accordion.test.tsx
  main/__tests__/__snapshots__/Accordion.test.tsx.snap
  stories/Icon.ts
  stories/assets/icons/arrowDown.svg
  stories/assets/icons/arrowUp.svg
  stories/dooboo-ui/Accordion.stories.tsx
Labels: refactor

#224 [Feature][Table] Add a DataTable feature
  main/__assets__/check.png
  main/index.ts
  packages/Tables/CHANGELOG.md
  packages/Tables/CheckBox.tsx
  packages/Tables/README.md
  packages/Tables/TableCell.tsx
  packages/Tables/TableHeader.tsx
  packages/Tables/TableRow.tsx
  packages/Tables/TableTitle.tsx
  packages/Tables/__assets__/mark.png
  packages/Tables/index.tsx
  packages/Tables/package.json
  packages/Tables/tsconfig.json
  packages/Tables/yarn.lock
  packages/__tests__/Tables.test.tsx
  packages/__tests__/__snapshots__/Tables.test.tsx.snap
  stories/index.ts
  stories/packages/Tables.stories.tsx
Labels: feature, packages

#229 Update README.md (expo-web)
  README.md
Labels: documentation

#227 [Feature][LineChart] Add main source, need review
  packages/Charts/CHANGELOG.md
  packages/Charts/LineChart/README.md
  packages/Charts/LineChart/index.tsx
  packages/Charts/LineChart/types.ts
  packages/Charts/README.md
  packages/Charts/index.tsx
  packages/Charts/package.json
  packages/Charts/tsconfig.json
  packages/Charts/yarn.lock
  packages/__tests__/LineChart.test.tsx
  packages/__tests__/__snapshots__/LineChart.test.tsx.snap
  stories/index.ts
  stories/packages/LineChart.stories.tsx
Labels: documentation, packages, wip

#232 [RadioButton]Change useState to useRef and some minor things
  main/RadioButton/index.tsx
  main/__tests__/__snapshots__/RadioButton.test.tsx.snap
Labels: enhancement, trivial

#233 [Enhance][Charts][LineChart] Update structure & Fix some hardcoded inconsistencies & fixed test code
  package.json
  packages/Charts/LineChart/README.md
  packages/Charts/LineChart/index.tsx
  packages/Charts/LineChart/types.ts
  packages/Charts/README.md
  packages/__tests__/LineChart.test.tsx
  packages/__tests__/__snapshots__/LineChart.test.tsx.snap
  stories/packages/LineChart.stories.tsx
Labels: enhancement, trivial

#234 [EditText]Refactoring EditText
  main/EditText/README.md
  main/EditText/index.tsx
  main/__tests__/EditText.test.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  stories/dooboo-ui/EditText.stories.tsx
Labels: enhancement

#237 [Button] Add mouse hover implement for Web
  main/Button/README.md
  main/Button/hooks/customHooks.ts
  main/Button/hooks/index.ts
  main/Button/hooks/utils/getNode.native.ts
  main/Button/hooks/utils/getNode.ts
  main/Button/index.tsx
  main/__tests__/Button.test.tsx
  main/__tests__/__snapshots__/Button.test.tsx.snap
  package.json
  stories/dooboo-ui/Button.stories.tsx
  yarn.lock
Labels: enhancement

#239 [bugfix/accordion] first rotate Animation not Working
  main/Accordion/AccordionItem.tsx
Labels: bugfix

#240 [Accordion]Update README
  main/Accordion/README.md
Labels: documentation

#241 [SearchInput] Refactor SearchInput
  main/SearchInput/README.md
  main/SearchInput/index.tsx
  main/__tests__/SearchInput.test.tsx
  main/__tests__/__snapshots__/SearchInput.test.tsx.snap
  stories/dooboo-ui/SearchInput.stories.tsx
Labels: documentation, enhancement

#243 [Enhance][Charts] Added horizontal grid lines
  packages/Charts/BarChart/index.tsx
  packages/Charts/LineChart/index.tsx
  yarn.lock
Labels: enhancement

#251 Add RTL option to SwitchToggle props
  main/SwitchToggle/README.md
  main/SwitchToggle/index.tsx
Labels: enhancement

#249 [Enhance][Theme] Color @dooboo/theme colors enhancement
  packages/theme/index.tsx
  packages/theme/theme.ts
Labels: enhancement

#255 [EditText] Refactor Storybook
  stories/dooboo-ui/EditText.stories.tsx
Labels: enhancement

#257 Update Accordion README.md
  main/Accordion/README.md
Labels: documentation

#261 Update Minor things like width, testID, EditTextInputType enum
  main/EditText/index.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  stories/dooboo-ui/EditText.stories.tsx
Labels: bugfix

#250 Implementation of Select dropdown component
  README.md
  main/Select/Arrow.tsx
  main/Select/CHANGELOG.md
  main/Select/Item.tsx
  main/Select/README.md
  main/Select/Select.tsx
  main/Select/index.tsx
  main/__tests__/Select.test.tsx
  main/__tests__/__snapshots__/Select.test.tsx.snap
  stories/dooboo-ui/Select.stories.tsx
  stories/index.ts
Labels: core, feature

#242 Calendar Carousel : code refactoring completed
  packages/CalendarCarousel/README.md
  packages/CalendarCarousel/index.tsx
  packages/__tests__/__snapshots__/CalendarCarousel.test.tsx.snap
  stories/assets/icons/left.png
  stories/assets/icons/right.png
  stories/index.ts
  stories/packages/CalendarCarousel.stories.tsx
Labels: feature

#260 Change url in contributing.md
  CONTRIBUTING.md
Labels: documentation

#262 Revert "Update Minor things like width, testID, EditTextInputType enum"
  main/EditText/README.md
  main/EditText/index.tsx
  main/__tests__/EditText.test.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  packages/__tests__/__snapshots__/CalendarCarousel.test.tsx.snap
  stories/dooboo-ui/EditText.stories.tsx
Labels: breaking, bug, core, regression

#264 Change box type to show signIn style and add 1 props which is contentStyle
  main/EditText/README.md
  main/EditText/index.tsx
  main/__tests__/__snapshots__/EditText.test.tsx.snap
  package.json
  stories/dooboo-ui/EditText.stories.tsx
Labels: enhancement

#268 Fixed Select README import example #267
  .github/workflows/labeler.yml
  main/Select/README.md
  main/SwitchToggle/index.tsx
Labels: documentation, enhancement, minor
